# Matrix Multiplication

In [1]:
import numpy as np
import random
A = np.random.randint(0,4,[3,1])
B= np.random.randint(0,4,[1,3])
print(np.shape(A),np.shape(B))
A,B

(3, 1) (1, 3)


(array([[2],
        [3],
        [0]]),
 array([[0, 0, 3]]))

In [2]:
C=np.dot(A,B)
print(C.shape)
C

(3, 3)


array([[0, 0, 6],
       [0, 0, 9],
       [0, 0, 0]])

# Transpose

In [3]:
#Transpose of a matrix
C.T

array([[0, 0, 0],
       [0, 0, 0],
       [6, 9, 0]])

# Solve Ax=B!

In [4]:

A=np.random.randint(0,4,[3,3])
B=np.random.randint(0,4,[3,1])
print (A)
print (B)
import numpy.linalg as LA
LA.solve(A,B)

[[0 2 1]
 [2 1 1]
 [2 0 2]]
[[2]
 [2]
 [0]]


array([[ 0.66666667],
       [ 1.33333333],
       [-0.66666667]])

# Find Inverse of a Matrix

In [5]:
#Ax=B . A_invAx=A_inverseB So x= A_inv.B
#Lets find Inverse of A
AI=LA.inv(A)
AI

array([[-0.33333333,  0.66666667, -0.16666667],
       [ 0.33333333,  0.33333333, -0.33333333],
       [ 0.33333333, -0.66666667,  0.66666667]])

In [6]:
#checking if inverse works
np.dot(AI,A)

array([[ 1.00000000e+00, -1.11022302e-16, -5.55111512e-17],
       [ 0.00000000e+00,  1.00000000e+00,  1.11022302e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

# Determinant of a Matrix

In [7]:
#Determinant (of a square matrix)
LA.det(A)

-6.0

# Eigenvalues and Eigenvectors

In [8]:
LA.eigvals(A)

array([-1.64575131,  3.64575131,  1.        ])

$Ax=\lambda x$

$(A-\lambda I)x=0$

$mod(A-\lambda I)=0$


In [9]:
#Gives you Eigenvalues and Eigenvectors
LA.eig(A)

(array([-1.64575131,  3.64575131,  1.        ]),
 array([[-0.79010332,  0.5029212 , -0.37139068],
        [ 0.43343786,  0.61117521, -0.55708601],
        [ 0.43343786,  0.61117521,  0.74278135]]))